Feature/push commit check
tech-university-india/k8s-designer-backend pull request #22
Opened 2023-03-04 19:56 UTC by dilipsingh27

2023-03-05 04:04 UTC, AshreneRoy approved these changes

2023-03-05 04:04 UTC, AshreneRoy commented on package.json
> +    "build": "echo building..."
Please give the actual build command. We have backend set up and working, so we should use actual commands

2023-03-05 04:04 UTC, AshreneRoy commented on src/constants/app.constants.js
> +const PROJECT_ROOT = '/';
This will take the system root, let it come from the env

2023-03-05 04:04 UTC, AshreneRoy commented on tmp/1/docker-compose.yaml
> +version: '3'
Please delete these tmp/ files and add the folder to .gitignore

2023-03-05 04:04 UTC, AshreneRoy commented on .github/workflows/pushCommitCheck.yml
> +  OWNER: ${{secrets.DOCKER_USERNAME}}
Are the secrets added to the repo? Is this tested?

2023-03-05 04:05 UTC, AshreneRoy requested changes

2023-03-05 04:05 UTC, AshreneRoy commented on .github/workflows/pushCommitCheck.yml
> +  OWNER: ${{secrets.DOCKER_USERNAME}}
Pls check

2023-03-05 05:01 UTC, dilipsingh27 commented on src/constants/app.constants.js
> +const PROJECT_ROOT = '/';
it says error on pushing the workflow to GitHub , since it getting project root from .env which is not getting pushed 
so it's not reading value from there and saying PROJECT_ROOT is undefined, it should be string that's why did that

2023-03-05 05:02 UTC, dilipsingh27 commented on .github/workflows/pushCommitCheck.yml
> +  OWNER: ${{secrets.DOCKER_USERNAME}}
Yes, they are added

2023-03-05 06:37 UTC, AshreneRoy commented
@dilipsingh27 there are merge conflicts

2023-03-11 08:39 UTC, AshreneRoy commented
@dilipsingh27 comments pending , pls resolve

2023-03-14 06:33 UTC, AshreneRoy approved these changes

2023-03-14 06:34 UTC, merged