Feat/backend prisma
tech-university-india/k8s-designer-backend pull request #5
Opened 2023-02-10 13:24 UTC by shashwath-sk

1.Integrated prisma orm to backend
2. Created k8s database and user table using prisma model
3. Added seeder for user model
4.for testing purpose created users route and corresponding controller and service.

2023-02-10 14:01 UTC, AshreneRoy requested changes

2023-02-10 14:01 UTC, AshreneRoy commented on prisma/schema.prisma
> +  id        String @id @default(uuid())
Check corresponding uuid data type in postgres, the migration sql seems to have generated text as datatype

2023-02-12 05:51 UTC, shashwath-sk commented on prisma/schema.prisma
> +  id        String @id @default(uuid())
yeah, In postgresql they are stored as text ,but their type is of string

2023-02-12 05:53 UTC, shashwath-sk commented on prisma/migrations/20230210114401_user_model/migration.sql
> +/*
okk, deleting user_model migration and modifying user_db migration so that it reflects current state of my local postgresql

2023-02-12 05:55 UTC, AshreneRoy commented on prisma/schema.prisma
> +  id        String @id @default(uuid())
https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/enable-native-database-functions

You will have to add postgres extension for UUID and map it to prisma

2023-02-12 06:21 UTC, shashwath-sk commented on prisma/schema.prisma
> +  id        String @id @default(uuid())
mapped pgcrypto extension to database through migration, can u please review my changes and let me any further changes required .

2023-02-12 12:10 UTC, AshreneRoy requested changes

2023-02-12 12:10 UTC, AshreneRoy commented on src/controllers/customer.controller.js
> +const services = require('../services/customer.services');
This file shouldn't be changed from what is in main, rebase your branch

2023-02-12 12:10 UTC, AshreneRoy commented on src/exceptions/customError.js
> +class httpError extends Error {
This file shouldnt be added back, it was removed, you might want to rebase against agrima's branch if your branch was cut from there

2023-02-12 12:10 UTC, AshreneRoy commented on src/middlewares/cutomerValidator.js
> +const httpConstants = require('http2').constants;
Same goes for this, it was removed

2023-02-12 12:10 UTC, AshreneRoy commented on src/routes/customer.routes.js
> +const routes = require('express').Router();
Same for this

2023-02-12 12:10 UTC, AshreneRoy commented on src/schemas/customerId.schema.js
> +const joi = require('joi');
This should also not be added back, it was removed(renamed)

2023-02-12 12:10 UTC, AshreneRoy commented on src/services/customer.services.js
> +const services = require('../services/customer.service');
Same for this

2023-02-12 12:10 UTC, AshreneRoy commented on prisma/migrations/20230212060617_user_model/migration.sql
> +CREATE TABLE "User" (
This should be generated as 'users', table names = plural, model names = singular in caps. You will have to add mapping in schema.prisma.

Also migration naming scheme should be followed: timestamp_action_table_name
`timestamp_create_users`

2023-02-12 12:10 UTC, AshreneRoy commented on prisma/schema.prisma
> +  full_name String
Camel casing for models, snake casing for sql tables, pls add mapping to convert camel case to snake case

eg:
```
industryId        Int                @map("industry_id")
```

2023-02-13 12:31 UTC, shashwath-sk commented on src/controllers/customer.controller.js
> +const services = require('../services/customer.services');
There was some problem while rebaseing,so i did changes manually through github,can you please review it and let  me know

2023-02-13 12:31 UTC, shashwath-sk commented on prisma/migrations/20230212060617_user_model/migration.sql
> +CREATE TABLE "User" (
added map in schema to map models name to table

2023-02-13 12:58 UTC, AshreneRoy requested changes

2023-02-13 12:58 UTC, AshreneRoy commented on prisma/schema.prisma
> +model user {
This should be Caps , model = singular and in first letter capitalised

2023-02-13 13:45 UTC, shashwath-sk commented on prisma/schema.prisma
> +model user {
model user renamed to User,
sorry this time i made a lot of error, i'll make sure this won't happen again.

2023-02-13 13:54 UTC, AshreneRoy approved these changes

2023-02-13 13:54 UTC, merged