Feat/zipping service
tech-university-india/k8s-designer-backend pull request #8
Opened 2023-02-16 18:11 UTC by ApoorvGit

PASS  tests/services/zipping.service.spec.js
 PASS  tests/middlewares/customer.middleware.spec.js
 PASS  tests/controllers/customer.controller.spec.js
 PASS  tests/services/customer.service.spec.js
-------------------------|---------|----------|---------|---------|-------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------|---------|----------|---------|---------|-------------------
All files                |     100 |      100 |     100 |     100 |                   
 controllers             |     100 |      100 |     100 |     100 |                   
  customer.controller.js |     100 |      100 |     100 |     100 |                   
 exceptions              |     100 |      100 |     100 |     100 |                   
  customer.exception.js  |     100 |      100 |     100 |     100 |                   
 middlewares             |     100 |      100 |     100 |     100 |                   
  request.middleware.js  |     100 |      100 |     100 |     100 |                   
 schemas                 |     100 |      100 |     100 |     100 |                   
  customer.schema.js     |     100 |      100 |     100 |     100 |                   
  index.schema.js        |     100 |      100 |     100 |     100 |                   
 services                |     100 |      100 |     100 |     100 |                   
  customer.service.js    |     100 |      100 |     100 |     100 |                   
  zipping.service.js     |     100 |      100 |     100 |     100 |                   
-------------------------|---------|----------|---------|---------|-------------------

Test Suites: 4 passed, 4 total
Tests:       12 passed, 12 total
Snapshots:   0 total
Time:        1.099 s
Ran all test suites.

=>created Archiver (Zip) service and tested it with 3 test cases (100% coverage)

2023-02-17 15:54 UTC, AshreneRoy requested changes

2023-02-17 15:54 UTC, AshreneRoy commented on src/services/zipping.service.js
> +    if (!fs.existsSync(resolvedFolderPath)) {
Lets use async file read, make this an async function, use promisified fs methods

2023-02-17 15:54 UTC, AshreneRoy commented on src/services/zipping.service.js
> +    });
Put this in a config - archiver.config.js. We will have one place to manage configs and also that way these methods can be mocked as well in the tests instead of having to create actual folders, zip and later removing them

2023-02-18 20:05 UTC, ApoorvGit commented
Made the required changes

2023-02-22 03:27 UTC, AshreneRoy approved these changes

2023-02-22 03:28 UTC, merged